### ISSUE TITLE
calc_score of candidate in bbs

### ISSUE THREAD

**Issue by narutojxl** [koide3/hdl_global_localization#5]
Hi author,
In code we use DiscreteTransformation::calc_score() to score each candidate, 
https://github.com/koide3/hdl_global_localization/blob/3586396a32c6b0c003a02d8cffe18e97723330a3/src/hdl_global_localization/bbs/bbs_localization.cpp#L59-L61
if we use the `transformed` points creates a grid_map with [OccupancyGridMap::insert_points()](https://github.com/koide3/hdl_global_localization/blob/master/include/hdl_global_localization/bbs/occupancy_gridmap.hpp#L31), and then comapre the difference pixel by pixel, and then sum the whole difference value. We also modify bbs_localization.cpp#L27, to `return score > rhs.score;`. The smaller difference, the better the candidate.  
Have you tried this scoring method?  Thanks for your help and time !

**Comment by koide3** [comment]
This algorithm finds the transformation that maximizes the log likelihood (e.g., num of *hit count*), thus the larger score, the better. We can reform it as a minimization problem by modifying ```DiscreteTransformation::operator<``` as well as ```OccupancyGridMap::pyramid_up```, but I suppose it doesn't make a significant difference on the branch pruning efficiency because it's just an inverse of the current formulation.

**Comment by narutojxl** [comment]
Thanks author :), my problem is solved.
